spring.application.name=task-manager-api

# Configurações do H2 Database (Banco em Memória)
spring.datasource.url=jdbc:h2:mem:taskmanagerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permitir acesso ao console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Chave secreta para o JWT (Exemplo)
jwt.secret=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
jwt.expiration=86400000